### ISSUE TITLE
Items (Power Ups)

### ISSUE THREAD

**Issue by Sqrli3** [Sqrli3/Expiry-Date#7]
**1.** An abstract class called "Item".

Item class must include a general Use() method, that is overridden by its sub classes.

Items must exist in the scene in some form, so that they may then be picked up by players.
(No models yet, but try and use icons & world space UI.)

**2.** A subclass of Item called "PowerUp".

Power Ups will apply a given buff to a specified player when the Use() method is called.

Power Up suggestions:

- Speed Boost
- Invincibility

**Note:**
What a "Speed Boost" or "Invincibility" bonus actually does is very dependant on the variables in the Player class. For developing this feature, please just create a stub Player class with the necessary variables "speed" (integer) and "invincible" (bool).

**Comment by DigyPT** [comment]
Power ups will be divided in 3 sections : ** Throwable/environment traps, Consumables and equipment **

**Throwable/environment traps** will be those that the player can throw and affect himself and other players (for example the **Jamtrap** that will **slow down** every player** inside the area);

**Consumables** will only affect the player that uses said consumable affecting his stats ( for example "candy" will **boost** player **speed** when used;

**Equipment** will be those items that will have more duration/uses per activation used to disrupt one player by another player ( for example, **the Rolling Pin** will be used to "steal" other players powerups;

**Current Power ups being develop**

**Throwable/environment traps**
    ->JamTrap: **slows** the player in that area; (done)
    ->HotSauce: **Increases** players speed in that area for a short amount of time (missing the short amount of time bit)
    ->Teddy bear bomb: Will **displace and stun ** player 
    -> Honey : Will **trap** the players during the duration

**Consumables**
   ->"Candy":Increases player **speed;**
   ->"Vitamins":player becomes immune;
   ->Cardboard":hides the player in the minimap, food doesnt run away from the player;
   ->WishBone: Locates the target , beeps when close;

**Equipment**
   ->RollingPin: drops the power ups of enemy players when they get hit
   ->Hammer : Smash Bros style , stuns enemy players.

More power ups could be added/removed in the future

**Comment by Sqrli3** [comment]
I feel equipment should be defined by the fact they are all melee weapons, not by their number of uses. Where Consumables apply effects to the user, and Throwables at range, "Equipment" applies to players in an AoE around and/or nearby the user.

Instead, the Item class already contains an integer variable called "uses" that increments down whenever the item is used, and destroys it at 0.
This can be utilized with subclass of Item at your discretion, not necessarily just Equipment.

Also, consider creating a separate class called "Obstacle" for environmental traps, and simply have said traps be instantiated as one of the various effects these items can create.
